### ISSUE TITLE
Plan out Summer Advanced GIS

### ISSUE THREAD

**Issue by dt-woods** [cga-wm/cga-wm.github.io#6]
# Part 1.1 "Introduction"

#### Day 1
* Introduction to the class
* Before we get started, there are some things we need to do on Blackboard (Bb).
    1. Getting Started assignment (**TASK**)
    1. Introduce yourselves via the discussion board (**TASK**)
* Review the syllabus (**VIDEO**)
    * Overview of course objectives
        - **DISCUSSION** - "GIS Developer or Specialist?"
          *What are some differences between a GIS developer and a GIS specialist? Be sure to include a link (or links) to references you cite.*
    * Expectations of students
    * Assessment (two oral evaluations)
    * Resources (e.g., [class website](https://cga-wm.github.io/course/adv-gis/index.html))
    * Communication - the mantra is "we work as a team"
        - GroupMe for instantaneous questions/answers/clarifications/confirmations (*fast*)
        - Bb Discussion Board for posing questions, sharing resources (links), etc. (*moderate*)
            + Discussion Question Responses (titled; respond to the question(s) with your answer and you reply to another post---e.g., the post before yours)
            + Issues (you create these to ask questions)
        - Email for personal communication and reminders (*slow*)
        - Zoom appointments for personal communication and evaluations
    * Technology
      You will need access to (**TASK**: install these now or check now that you can access them):
        - [GroupMe](https://groupme.com/en-US/apps) app for fast communication amongst the team
        - [Zoom](https://cwm.zoom.us/) for "face-to-face" meetings and evaluations
        - [VDI](https://www.wm.edu/offices/it/services/network/virtualdesktop/index.php) to use ArcGIS Pro, ArcMap, and/or QGIS if your computer does not (and can not) have it; otherwise, follow the instructions for [installing ArcGIS Pro](https://www.wm.edu/as/cga/arcgis-licensing/index.php) and QGIS on your own machine
        - [ArcGIS Online](https://www.arcgis.com/index.html) w/ Notebook (see to-do item for custom user roles)
* Project 1
    * Link to website that reviews the project
    * Introduction **VIDEO**. This is the first of two projects. 
    * **DISCUSSION** - "Election Data" 
      *Find data associated with the upcoming election, describe the data (e.g., geometry, CRS, attributes, etc.), describe how it relates to the election, and share a link to it on discussion board.*
    * Introduction to Geoethics (**VIDEO**)
    * **DISCUSSION** - "The Geoethics of Election 2020"
      *What are some geoethical concerns that may arise with the upcoming presidential election? Be sure to include a definition of geoethics (include a link).*

#### Day 2
* Ice Breaker Challenge (**VIDEO**)
    * **TASK** - start/create a process document to track what you do, how you do it, and how long it takes you to do it
    * **DISCUSSION** - "Ice Breaker - Part 1"
        *(as soon as the prompt is released) Brainstorm your methodology. What do you need to do? What are your priorities? How are you going to tackle this challenge?* 
        
#### Day 3 
* **DISCUSSION** - "Ice Breaker - Part 2"
  *(following completion) What was your process? How did your priorities change throughout the process? What did you find challenging? What resources did you use/find helpful?*
* Introduction to Graphical Models (**VIDEO**)
    * This should tie into the Ice Breaker Challenge
    * This can be done with both ArcGIS Pro (i.e., ModelBuilder) and QGIS (e.g., [Processing Modeler](https://www.qgistutorials.com/en/docs/3/processing_graphical_modeler.html))
    * See CGA YouTube video ["Getting Started with Model Builder"](https://youtu.be/KtgAQXEJLHk)
* **TASK** - create a graphical model that does x, y, and z using ArcGIS/QGIS
* Graphical Models - Part 2 (**VIDEO**)
  Note that graphical models are just programs.
* **DISCUSSION** - "Programming (huh!). What is it good for?"

## Discussions
1. "GIS Developer or Specialist"
1. "Election Data"
1. "The Geoethics of Election 2020"
1. "Ice Breaker - Part 1"
1. "Ice Breaker - Part 2"
1. "Programming (huh!). What is it good for?"

## Tasks
1. Topic Research - "You have been hired as a GIS expert to assist in analyzing geospatial data associated with Election 2020 for the new president of the United States. Etc. etc."
    - Deliverables include discussion posts and an example dataset/map (link/URL)
1. Ice Breaker Challenge (see below) + learning how to use discussion boards +/- using VDI
    - Deliverables include a discussion post (see prompt), using the Issues discussion board, and creating a process document
1. Looking into graphical process models (in ArcPro and QGIS)
    - ModelBuilder
    - [Processing Modeler](https://www.qgistutorials.com/en/docs/3/processing_graphical_modeler.html)
1. Linking graphical modeling to programming
    - Intro to Notebooks
    - Intro to Markdown
    - Intro to Python

## Videos/How To's
1. Overview of syllabus and resources
1. How to connect to VDI. (*for accessing ArcGIS Pro and QGIS*)
    - [How to access VDI from Mac (YouTube)](https://youtu.be/lG43GtH1Ta4)
    - [How to access VDI from Windows (YouTube)](https://youtu.be/pZh-fMoaV54)

## Ice Breaker Challenge
Prepare a challenge question that will reaffirm their base knowledge (see syllabus) and have them problem solving (use Bb discussion boards as help channels).

## To Do Items
- [ ] Make instructions for installing QGIS/accessing it via VDI (see how-to videos)
- [ ] Make instructions for use of Bb discussion boards (e.g., 
    - type up your response ahead of time (do not type original ideas in the Bb discussion board post space; it can delete your text without saving!)
    - only post when you have your content ready
    - after you have posted your response, read and respond to the person's post ahead of yours; use the "reply" and/or quote text
- [x] Add "Code of Conduct" section to syllabus for discussion boards
- [ ] Create an assignment for Graphical Process Modelling that requires the use of both ArcGIS and QGIS
- [x] Develop scenario 1 "Election 2020"
- [x] Email students with new syllabus; point out the expectations for their base knowledge and access to technology.
- [ ] Draft example for GIS process document (see task 1)
- [x] Create custom user roles in AGOL for your students (not sure if Notebooks will be out of beta before class begins)
- [x] Create introduction video for syllabus, assessment, and resources (e.g., cg-wm.github.io)
- [x] Create new web page for "Election 2020" 
- [x] Create a recurring Zoom meeting w/ password for students and allow them to enter w/o moderator

# Part 1.2 "Programming & Data"
Applying some fundamental programming to tackle the ugly, the tiresome, the dirty data.

## Discussions
1. TBA

## Tasks
1. Data IO
1. Data manipulation
1. Data types
1. Data analysis

## Videos/How To's
- https://courses.spatialthoughts.com/pyqgis-in-a-day.html

## Challenge
?

## To Do Items
- [ ] TBA

# Part 1.3 "Programming & Analysis"
See how programming can drive GIS.

## Tasks
1. Developing a custom process (e.g., toolbox in ArcGIS Pro or [QGIS](https://courses.spatialthoughts.com/pyqgis-in-a-day.html))

# Part 2 "Programming & The Web"
See how programming can be used in a new GIS context.

## Discussions
1. What are geoethics?
## Tasks
1. Create an ethics podcast
   - See examples from last semester on [blog](https://cga-wm.github.io/course/adv-gis/2020-05-14-end-of-semester.html)
1. Complete developers for ArcGIS tutorials (ArcGIS/Javascript/Arcade API)
1. Create a web app

# Miscellaneous
- Try GroupMe text app for rapid communication
